Temporarily disable externalscripts test.

diff --git a/Dockerfile.template.bottom b/Dockerfile.template.bottom
--- a/Dockerfile.template.bottom
+++ b/Dockerfile.template.bottom
@@ -114,7 +114,8 @@ RUN  cd ${SRCDIR}/ts_standardscripts && \
 RUN  cd ${SRCDIR}/ts_externalscripts && \
       source ${SALSTACK} && \
       setup ts_externalscripts -t current && \
-      scons || (echo 'SCONS FAILED: running pytest' && pytest --lf)
+      scons || (echo 'SCONS FAILED: running pytest' && pytest --lf) || \
+      echo "IGNORING FAILURE PER TIAGO 27072020 ##FIXME##"
 RUN  cd ${SRCDIR}/ts_scriptqueue && \
       source ${SALSTACK} && \
       setup ts_scriptqueue -t current && \
