standardscripts depends on ATMCSSimulator

diff --git a/Dockerfile.template b/Dockerfile.template
--- a/Dockerfile.template
+++ b/Dockerfile.template
@@ -193,6 +193,14 @@ RUN  cd ${SRCDIR}/ts_simactuators && \
       setup ts_simactuators -t current && \
       unset LD_PRELOAD && \
       scons || echo "Building ts_simactuators failed: ignoring"
+RUN  cd ${SRCDIR}/ts_ATMCSSimulator && \
+      source ${SALSTACK} && \
+      setup ts_salobj -t current && \
+      setup ts_config_attcs -t current && \
+      eups declare -r . ts_ATMCSSimulator -t current && \
+      setup ts_ATMCSSimulator -t current && \
+      unset LD_PRELOAD && \
+      scons || echo "Building ATMCSSimulator failed: ignoring"
 RUN  cd ${SRCDIR}/ts_scriptqueue && \
       source ${SALSTACK} && \
       setup ts_sal -t current && \
@@ -233,14 +241,6 @@ RUN  cd ${SRCDIR}/ts_ATDomeTrajectory && \
       setup ts_ATDomeTrajectory -t current && \
       unset LD_PRELOAD && \
       scons || echo "Building ATDomeTrajectory failed: ignoring"
-RUN  cd ${SRCDIR}/ts_ATMCSSimulator && \
-      source ${SALSTACK} && \
-      setup ts_salobj -t current && \
-      setup ts_config_attcs -t current && \
-      eups declare -r . ts_ATMCSSimulator -t current && \
-      setup ts_ATMCSSimulator -t current && \
-      unset LD_PRELOAD && \
-      scons || echo "Building ATMCSSimulator failed: ignoring"
 RUN  cd ${SRCDIR}/ts_externalscripts && \
       source ${SALSTACK} && \
       setup ts_sal -t current && \
