Update SAL versions

diff --git a/Dockerfile.template b/Dockerfile.template
--- a/Dockerfile.template
+++ b/Dockerfile.template
@@ -15,7 +15,7 @@ RUN  yum repolist && \
       yum install -y https://centos7.iuscommunity.org/ius-release.rpm
 ARG  d2u_v="-6.0.3-7.el7"
 ARG  iproute_v="-4.11.0-25.el7"
-ARG  java_v="-1:1.8.0.232.b09-0.el7_7.x86_64"
+ARG  java_v="-1:1.8.0.242.b08-0.el7_7.x86_64"
 ARG  osplice_v="-6.9.0-4"
 RUN  yum install -y --enablerepo=extras \
       "dos2unix${d2u_v}" \
@@ -70,7 +70,7 @@ RUN source ${LOADSTACK} && \
       "pycodestyle==${pycdst_v}" \
       "sqlalchemy==${sqlal_v}" \
       "boto3==${boto3_v}" \
-      "moto==${moto_v}"      
+      "moto==${moto_v}"
 ENV SRCDIR=/opt/lsst/src
 RUN mkdir -p /opt/lsst/sal
 ENV LSST_SDK_INSTALL=${SRCDIR}/ts_sal
@@ -81,17 +81,16 @@ ENV SALSTACK=/opt/lsst/sal/salbldsteps.bash
 ENV LD_PRELOAD=""
 
 #### Now move on to SAL object builds
-
 ARG config_ocs_v="v0.4.0"
 ARG sal_v="v4.0.0"
-ARG salobj_v="v5.3.0"
-ARG xml_v="v4.6.0"
+ARG salobj_v="v5.4.0"
+ARG xml_v="v4.7.0"
 ARG idl_v="v1.1.0"
 ARG config_attcs_v="v0.2.0"
-ARG scriptqueue_v="v2.4.0"
+ARG scriptqueue_v="v2.5.0"
 ARG externalscripts_v="v0.2.1"
-ARG standardscripts_v="v0.9.1"
-ARG ATDome_v="v0.10.0"
+ARG standardscripts_v="v0.10.0"
+ARG ATDome_v="v1.1.0"
 ARG ATDomeTrajectory_v="v1.2.0"
 ARG ts_simactuators_v="v0.2.0"
 ARG ATMCSSimulator_v="v0.10.1"
@@ -145,7 +144,7 @@ RUN  cd ${LSST_SDK_INSTALL} && \
       setup ts_idl -t current && \
       unset LD_PRELOAD && \
       make_idl_files.py $(ls ${TS_XML_DIR}/sal_interfaces | \
-        grep -v xml | tr '\n' ' ')
+        grep -v xml | grep -v MTM1M3 | grep -v HVAC | tr '\n' ' ')
 RUN  cd ${SRCDIR} && \
       mkdir dds && \
       cd dds && \
@@ -179,22 +178,23 @@ RUN  cd ${SRCDIR}/ts_simactuators && \
       source ${SALSTACK} && \
       eups declare -r . ts_simactuators -t current && \
       setup ts_simactuators -t current && \
-      scons || (echo 'SCONS FAILED: running py.test' && py.test)      
+      scons || (echo 'SCONS FAILED: running py.test' && py.test)
 RUN  cd ${SRCDIR}/ts_ATMCSSimulator && \
       source ${SALSTACK} && \
       eups declare -r . ts_ATMCSSimulator -t current && \
       setup ts_ATMCSSimulator -t current && \
-      scons || (echo 'SCONS FAILED: running py.test' && py.test)      
+      scons || (echo 'SCONS FAILED: running py.test' && py.test)
+ENV  LSST_DDS_DOMAIN=citest
 RUN  cd ${SRCDIR}/ts_ATDome && \
       source ${SALSTACK} && \
       eups declare -r . ts_ATDome -t current && \
       setup ts_ATDome -t current && \
-      scons || (echo 'SCONS FAILED: running py.test' && py.test)      
+      scons || (echo 'SCONS FAILED: running py.test' && py.test)
 RUN  cd ${SRCDIR}/ts_ATDomeTrajectory && \
       source ${SALSTACK} && \
       eups declare -r . ts_ATDomeTrajectory -t current && \
       setup ts_ATDomeTrajectory -t current && \
-      scons || (echo 'SCONS FAILED: running py.test' && py.test)      
+      scons || (echo 'SCONS FAILED: running py.test' && py.test)
 RUN  cd ${SRCDIR}/ts_standardscripts && \
       source ${SALSTACK} && \
       eups declare -r . ts_standardscripts -t current && \
@@ -204,12 +204,12 @@ RUN  cd ${SRCDIR}/ts_externalscripts && \
       source ${SALSTACK} && \
       eups declare -r . ts_externalscripts -t current && \
       setup ts_externalscripts -t current && \
-      scons || (echo 'SCONS FAILED: running py.test' && py.test)      
+      scons || (echo 'SCONS FAILED: running py.test' && py.test)
 RUN  cd ${SRCDIR}/ts_scriptqueue && \
       source ${SALSTACK} && \
       eups declare -r . ts_scriptqueue -t current && \
       setup ts_scriptqueue -t current && \
-      scons || (echo 'SCONS FAILED: running py.test' && py.test)      
+      scons || (echo 'SCONS FAILED: running py.test' && py.test)
 # Make the "LSST" kernel set up ts_sal objects too
 COPY sal_lsstlaunch.bash ${jl}/lsstlaunch.bash
 
