standardscripts comes before scriptqueue

diff --git a/Dockerfile.template b/Dockerfile.template
--- a/Dockerfile.template
+++ b/Dockerfile.template
@@ -193,6 +193,20 @@ RUN  cd ${SRCDIR}/ts_simactuators && \
       setup ts_simactuators -t current && \
       unset LD_PRELOAD && \
       scons || echo "Building ts_simactuators failed: ignoring"
+RUN  cd ${SRCDIR}/ts_standardscripts && \
+      source ${SALSTACK} && \
+      setup ts_sal -t current && \
+      setup ts_salobj -t current && \
+      setup ts_scriptqueue -t current && \
+      make_salpy_libs.py Electrometer ATPtg ATCamera \
+       ATMonochromator ATSpectrograph FiberSpectrograph && \
+      eups declare -r . ts_standardscripts -t current && \
+      setup ts_config_attcs -t current && \
+      setup ts_config_ocs -t current && \
+      setup ts_ATMCSSimulator -t current && \
+      setup ts_standardscripts -t current && \
+      unset LD_PRELOAD && \
+      scons || echo "Building standardscripts failed: IGNORING"
 RUN  cd ${SRCDIR}/ts_scriptqueue && \
       source ${SALSTACK} && \
       setup ts_sal -t current && \
@@ -227,20 +241,6 @@ RUN  cd ${SRCDIR}/ts_ATMCSSimulator && \
       setup ts_ATMCSSimulator -t current && \
       unset LD_PRELOAD && \
       scons || echo "Building ATMCSSimulator failed: ignoring"
-RUN  cd ${SRCDIR}/ts_standardscripts && \
-      source ${SALSTACK} && \
-      setup ts_sal -t current && \
-      setup ts_salobj -t current && \
-      setup ts_scriptqueue -t current && \
-      make_salpy_libs.py Electrometer ATPtg ATCamera \
-       ATMonochromator ATSpectrograph FiberSpectrograph && \
-      eups declare -r . ts_standardscripts -t current && \
-      setup ts_config_attcs -t current && \
-      setup ts_config_ocs -t current && \
-      setup ts_ATMCSSimulator -t current && \
-      setup ts_standardscripts -t current && \
-      unset LD_PRELOAD && \
-      scons || echo "Building standardscripts failed: IGNORING"
 RUN  cd ${SRCDIR}/ts_externalscripts && \
       source ${SALSTACK} && \
       setup ts_sal -t current && \
